# Generated by Django 5.2.15 on 2026-06-29 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled_globally', models.BooleanField(default=False)),
                ('percentage_rollout', models.IntegerField(default=0, help_text='0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_for_orgs', models.ManyToManyField(blank=True, related_name='enabled_flags', to='organizations.organization')),
                ('enabled_for_users', models.ManyToManyField(blank=True, related_name='enabled_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
