name: Feature Request
description: Suggest a new feature for DjangoForge
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem this solves
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: dropdown
    id: pr
    attributes:
      label: Would you submit a PR?
      options:
        - "Yes"
        - "No"
        - "Maybe"
    validations:
      required: true
